plbr_update_initial: true
plbr_update_continuous: true

plbr_firewall_profiles: {
  "Domain": {"enabled": "False", "inbound": "allow", "outbound": "allow"},
  "Public": {"enabled": "False", "inbound": "allow", "outbound": "allow"},
  "Private": {"enabled": "False", "inbound": "allow", "outbound": "allow"},
}
# enabled: True, False, NotConfigured
# inbound: Block, Allow, NotConfigured
# outbound: Block, Allow, NotConfigured
# key: ["Domain", "Private", "Public"], 


plbr_windows_defender: true
windows_defender_exclusions: ["c:\\tools", "c:\\users"]
# 0: UAC won't prompt (like disabled)                                                                                                                                                                  │
# 1: ask for username and password to execute the binary with high rights (on Secure Desktop)                                                                                                          │
# 2: Always notify me ask for confirmation to the administrator when he tries to execute something with high privileges (on Secure Desktop)                                                            │
# 3: like 1 but not necessary on Secure Desktop                                                                                                                                                        │
# 4: like 2 but not necessary on Secure Desktop                                                                                                                                                        │
# 5: ask the administrator to confirm to run non Windows binaries with high privileges     
plbr_uac_level: 0

plbr_enable_run_as_ppl: false

plbr_cis_hardening: false