- name: Add jubeaz to audio
  ansible.builtin.user:
    name: jubeaz
    groups: audio
    append: true

- name: Enable audio services
  ansible.builtin.systemd:
    name: {{ item }}
    scope: user
    enabled: true
    state: started
    daemon_reload: true
  become: false
  with_items:
    - pipewire 
    - pipewire-pulse 
    - wireplumber
