# ######################
# gen-locale vars
# ######################
locales_gen: ["en_US.UTF-8 UTF-8", "fr_FR.UTF-8 UTF-8"]
  #locales_gen: ["en_US.UTF-8 UTF-8", "fr_FR.UTF-8 UTF-8"]
vconsole_content: ["KEYMAP=fr", "XKBLAYOUT=fr"]
locale_lang: en_US.UTF-8


