pacman_upgrade_ingore_list_str: ""
pacman_aur_directory: /usr/src/aur
pacman_aur_owner: jubeaz
pacman_aur_group: jubeaz
pacman_extra_args: ""
# pacman_extra_args: "--ignore {{ pacman_upgrade_ingore_list_str }}"
aur_directory: "{{ pacman_aur_directory }}"
aur_owner: "{{ pacman_aur_owner }}"
aur_group: "{{ pacman_aur_group }}"