# ######################
# time-sync vars
# ######################
tz_timezone: Europe/Paris
tz_ntp_servers: "0.fr.pool.ntp.org 1.fr.pool.ntp.org 2.fr.pool.ntp.org 3.fr.pool.ntp.org"
tz_ntp_distance_max: 24hr

