galaxy_info:
  role_name: minidlna
  author: jubeaz
  description: Install minidlna
  license: GPL-2.0-or-later
  min_ansible_version: 2.1
  platforms:
    - name: Ubuntu
      versions:
        - focal
    - name: Archlinux
      versions:
        - all
  galaxy_tags: []
dependencies: []
