galaxy_info:
  role_name: reflector
  author: jubeaz
  description: Install reflector
  license: GPL-2.0-or-later
  min_ansible_version: 2.1
  platforms:
    - name: Archlinux
      versions:
        - all
  galaxy_tags: []
dependencies: []
